name: E2E Tests

on:
  push:
    branches:

jobs:
  minikube:
    name: K8S
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes: [v1.23.0,v1.12.0]
    env:
      K8S_VERSION: ${{ matrix.kubernetes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Minikube-Kubernetes
        uses: manusa/actions-setup-minikube@v2.4.3
        with:
          minikube version: v1.24.0
          kubernetes version: ${{ matrix.kubernetes }}
          github token: ${{ secrets.GITHUB_TOKEN }}
          start args: '--addons=metrics-server --force'
      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Gradle Build
        if: success()
        run: ./gradlew build -PskipPublishing
      - name: Sonar Analysis
        if: success() && startsWith(matrix.kubernetes, 'v1.23')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew jacocoRootReport sonarqube -PskipPublishing
          -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }}
