name: E2E Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  minikube:
    name: K8S
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes: [v1.28.2,v1.27.6,v1.26.9,v1.25.14]
    env:
      K8S_VERSION: ${{ matrix.kubernetes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Minikube-Kubernetes
        uses: manusa/actions-setup-minikube@v2.9.0
        with:
          minikube version: v1.31.2
          kubernetes version: ${{ matrix.kubernetes }}
          github token: ${{ secrets.GITHUB_TOKEN }}
          start args: '--addons=metrics-server'
            # --extra-config=apiserver.runtime-config=api/beta=true'
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Gradle Build
        if: success()
        run: ./gradlew build -PskipPublishing
      - name: Sonar Analysis
        if: success() && startsWith(matrix.kubernetes, 'v1.28')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew -Dorg.gradle.jvmargs=-Xmx512m jacocoRootReport sonar -PskipPublishing
          -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }}
