name: Kubernetes Dashboard

on:
  push:
    branches:

jobs:
  publish-image:
    name: Publish Kubernetes Dashboard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build and Push
        working-directory: ./quickstarts/quarkus-dashboard
        run: |
          mvn -Pbuild-frontend,k8s clean package k8s:build k8s:push   \
          -Djkube.docker.push.username=${{ secrets.DOCKER_USERNAME }}      \
          -Djkube.docker.push.password=${{ secrets.DOCKER_PASSWORD }}
